package clientapi

import (
	"context"
	"regexp"
	"strings"
	"time"

	"github.com/myfedi/gargoyle/domain/models"
	"github.com/myfedi/gargoyle/domain/models/domainerrors"
	apUsecases "github.com/myfedi/gargoyle/domain/usecases/activitypub"
)

// CreateStatus creates a local Note through the ActivityPub outbox workflow so
// client posting and federation posting share the same normalization,
// persistence, and fan-out semantics.
func (u Statuses) CreateStatus(ctx context.Context, account *models.Account, input CreateStatusInput) (*CreateStatusResult, *domainerrors.DomainError) {
	if derr := requireAccount(account); derr != nil {
		return nil, derr
	}

	if strings.TrimSpace(input.Content) == "" {
		return nil, domainerrors.New(domainerrors.ErrBadRequest, "status is required")
	}

	// IDs are generated by a domain port so the use case does not depend on
	// infrastructure clocks, routes, or storage details.
	activityID, err := u.deps.IDGenerator.NewID()
	if err != nil {
		return nil, domainerrors.NewErr(domainerrors.ErrInternal, err)
	}
	objectID, err := u.deps.IDGenerator.NewID()
	if err != nil {
		return nil, domainerrors.NewErr(domainerrors.ErrInternal, err)
	}

	visibility := normalizedVisibility(input.Visibility)
	mentions, derr := u.resolveMentions(ctx, account, input.Content)
	if derr != nil {
		return nil, derr
	}
	if visibility == "direct" && len(mentions) == 0 {
		return nil, domainerrors.New(domainerrors.ErrBadRequest, "direct statuses require at least one mentioned recipient")
	}

	media, derr := u.statusMedia(ctx, account, input.MediaIDs)
	if derr != nil {
		return nil, derr
	}
	pollOptions, pollExpiresAt, derr := pollInput(input.ObjectType, input.PollOptions, input.PollExpiresIn)
	if derr != nil {
		return nil, derr
	}
	// Build an ActivityPub Note document, then hand off persistence and outbox
	// normalization to the ActivityPub use case. This keeps client API behavior
	// aligned with federation behavior instead of duplicating business rules here.
	raw, derr := u.statusNoteJSON(ctx, account, input, visibility, mentions, media, pollOptions, pollExpiresAt)
	if derr != nil {
		return nil, derr
	}

	res, derr := u.deps.CreateOutboxUC.CreateOutboxActivity(ctx, apUsecases.CreateOutboxActivityInput{
		Username:   account.Username,
		RawJSON:    raw,
		ActivityID: activityID,
		ObjectID:   objectID,
		Media:      media,
		Mentions:   mentions,
	})
	if derr != nil {
		return nil, derr
	}
	extracted, ok := apUsecases.ExtractNote(res.RawJSON)
	if !ok {
		return nil, domainerrors.New(domainerrors.ErrInternal, "created activity did not contain a note")
	}

	note := res.Note
	if note == nil {
		loaded, err := u.deps.NotesRepo.GetNoteByURI(ctx, nil, extracted.URI)
		if err != nil {
			return nil, domainerrors.NewErr(domainerrors.ErrInternal, err)
		}
		note = loaded
	}
	note.Visibility = visibility
	note.Sensitive = input.Sensitive
	note.SpoilerText = input.SpoilerText
	note.PollMultiple = input.PollMultiple
	note.PollExpiresAt = pollExpiresAt
	return &CreateStatusResult{
		Note:            *note,
		Account:         res.Account,
		Media:           media,
		Mentions:        res.Mentions,
		RawJSON:         res.RawJSON,
		FollowerInboxes: res.FollowerInboxes,
		MentionInboxes:  res.MentionInboxes,
	}, nil
}

// statusNoteJSON translates client create-status input into the Note shape
// accepted by the ActivityPub outbox use case. It only uses domain ports.
func (u Statuses) statusNoteJSON(
	ctx context.Context,
	account *models.Account,
	input CreateStatusInput,
	visibility string,
	mentions []models.Account,
	media []models.MediaAttachment,
	pollOptions []string,
	pollExpiresAt *time.Time,
) ([]byte, *domainerrors.DomainError) {
	inReplyToURI := ""
	if input.InReplyToID != "" {
		parent, err := u.deps.NotesRepo.GetNoteByID(ctx, nil, input.InReplyToID)
		if err != nil || parent.LocalAccountID != account.ID {
			return nil, domainerrors.New(domainerrors.ErrBadRequest, "in_reply_to_id is invalid")
		}
		inReplyToURI = parent.URI
	}
	return apUsecases.BuildStatusObjectJSON(apUsecases.StatusDocumentInput{Account: *account, Content: input.Content, ObjectType: input.ObjectType, Visibility: visibility, Sensitive: input.Sensitive, SpoilerText: input.SpoilerText, InReplyToURI: inReplyToURI, Media: media, Mentions: mentions, PollOptions: pollOptions, PollMultiple: input.PollMultiple, PollExpiresAt: pollExpiresAt, Host: u.deps.Host})
}

func (u Statuses) statusMedia(ctx context.Context, account *models.Account, mediaIDs []string) ([]models.MediaAttachment, *domainerrors.DomainError) {
	media := make([]models.MediaAttachment, 0, len(mediaIDs))
	seen := map[string]bool{}
	for _, mediaID := range mediaIDs {
		mediaID = strings.TrimSpace(mediaID)
		if mediaID == "" || seen[mediaID] {
			continue
		}
		seen[mediaID] = true
		item, err := u.deps.MediaRepo.GetMediaAttachmentByID(ctx, nil, mediaID)
		if err != nil || item.LocalAccountID != account.ID {
			return nil, domainerrors.New(domainerrors.ErrBadRequest, "media_ids contains invalid media")
		}
		media = append(media, *item)
	}
	return media, nil
}

func contentHashtags(content string) []string {
	seen := map[string]bool{}
	res := []string{}
	for _, match := range hashtagPattern.FindAllStringSubmatch(content, -1) {
		name := match[2]
		key := strings.ToLower(name)
		if name != "" && !seen[key] {
			seen[key] = true
			res = append(res, name)
		}
	}
	return res
}

func pollInput(objectType string, rawOptions []string, expiresIn int) ([]string, *time.Time, *domainerrors.DomainError) {
	if apUsecases.NormalizeStatusObjectType(objectType) != "Question" {
		return nil, nil, nil
	}
	options := make([]string, 0, len(rawOptions))
	seen := map[string]bool{}
	for _, option := range rawOptions {
		option = strings.TrimSpace(option)
		if option == "" || seen[strings.ToLower(option)] {
			continue
		}
		seen[strings.ToLower(option)] = true
		options = append(options, option)
	}
	if len(options) < 2 {
		return nil, nil, domainerrors.New(domainerrors.ErrBadRequest, "polls require at least two options")
	}
	if len(options) > 4 {
		return nil, nil, domainerrors.New(domainerrors.ErrBadRequest, "polls support up to four options")
	}
	if expiresIn <= 0 {
		expiresIn = 24 * 60 * 60
	}
	if expiresIn < 300 || expiresIn > 14*24*60*60 {
		return nil, nil, domainerrors.New(domainerrors.ErrBadRequest, "poll expiration must be between 5 minutes and 14 days")
	}
	expiresAt := time.Now().UTC().Add(time.Duration(expiresIn) * time.Second)
	return options, &expiresAt, nil
}

var remoteMentionPattern = regexp.MustCompile(`@([A-Za-z0-9_]+)@([A-Za-z0-9.-]+)`)

func (u Statuses) resolveMentions(ctx context.Context, account *models.Account, content string) ([]models.Account, *domainerrors.DomainError) {
	matches := remoteMentionPattern.FindAllStringSubmatch(content, -1)
	mentions := make([]models.Account, 0, len(matches))
	seen := map[string]bool{}
	for _, match := range matches {
		username := match[1]
		domain := strings.ToLower(match[2])
		acct := username + "@" + domain
		if seen[acct] {
			continue
		}
		seen[acct] = true
		if domain == strings.ToLower(u.deps.Domain) {
			local, err := u.deps.AccountsRepo.GetLocalAccountByUsername(ctx, nil, username)
			if err == nil {
				mentions = append(mentions, *local)
			}
			continue
		}
		remote, err := u.resolveAndCacheRemoteAccount(ctx, acct, account)
		if err == nil {
			mentions = append(mentions, *remote)
		}
	}
	return mentions, nil
}

var hashtagPattern = regexp.MustCompile(`(^|\s)#([\p{L}\p{N}_]{1,64})`)

func normalizedVisibility(visibility string) string {
	switch visibility {
	case "public", "unlisted", "private", "direct":
		return visibility
	default:
		return "public"
	}
}
